/* Initial set-up of the covid_vaccinations table that will contain 
records from 'Our World in Data''s COVID-19 data up to September 8th, 2022. */

CREATE TABLE covid_vaccinations
(iso_code varchar,
continent varchar,
"location" varchar,
"date" date,
new_tests int,
total_tests_per_thousand numeric,
new_tests_per_thousand numeric,
new_tests_smoothed int,
new_tests_smoothed_per_thousand numeric,
positive_rate numeric,
tests_per_case numeric,
tests_units varchar,
total_vaccinations int,
people_vaccinated int,
people_fully_vaccinated int,
total_boosters int,
new_vaccinations int,
new_vaccinations_smoothed int,
total_vaccinations_per_hundred numeric,
people_vaccinated_per_hundred numeric,
people_fully_vaccinated_per_hundred numeric,
total_boosters_per_hundred numeric,
new_vaccinations_smoothed_per_million int,
new_people_vaccinated_smoothed int,
new_people_vaccinated_smoothed_per_hundred numeric,
stringency_index numeric,
population_density numeric,
median_age numeric,
aged_65_older numeric,
aged_70_older numeric,
gdp_per_capita numeric,
extreme_poverty numeric,
cardiovasc_death_rate numeric,
diabetes_prevalence numeric,
female_smokers numeric,
male_smokers numeric,
handwashing_facilities numeric,
hospital_beds_per_thousand numeric,
life_expectancy numeric,
human_development_index numeric,
excess_mortality_cumulative_absolute numeric,
excess_mortality_cumulative numeric,
excess_mortality numeric,
excess_mortality_cumulative_per_million	numeric																				
);